- nrrd.py
When using _format_optional_nrrdvector with a valid vector, the warning 
> FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
will appear because the vector is being compared to a string. Compare to None type instead
> Fix warning in _format_optional_nrrdvector

- nrrd.py
- tests/test_nrrd.py
In `read_header`, each line of the nrrdfile was decoded to ASCII. The `decode` function is only defined for a byte string (A.K.A when you open with 'b' suffix). An error occurs if you input a string list, such as the example given in docstring of `read_header`:
```
>>> read_header(("NRRD0005", "type: float", "dimension: 3"))
{u'type': 'float', u'dimension': 3, u'keyvaluepairs': {}}
>>> read_header(("NRRD0005", "my extra info:=my : colon-separated : values"))
{u'keyvaluepairs': {u'my extra info': u'my : colon-separated : values'}}
```
The error is: `AttributeError: 'str' object has no attribute 'decode'`
This PR fixes by checking if the data given has a decode attribute and if so the object will be decoded. This is ideal because a bytes or bytesarray could be given, both of which can be …
> Fix string decode in read_header

- nrrd.py
- tests/test_nrrd.py
Using pynrrd to load data gave me a deprecation warning:
/opt/updated-python3/lib/python3.5/site-packages/nrrd.py:267: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
data = np.fromstring(decompressed_data[byteskip:], dtype)
After forking and running your tests, I stumbled upon a second deprecation warning (assertRaisesRegexp vs. assertRaisesRegex).
I updated both. Tests are still running.
> Two deprecations

- nrrd.py
- tests/test_nrrd.py
This is sort of discussed in #37
Added new functions for parsing (converting from NRRD string to Python equivalent type) and formatting (conversion from Python equivalent type to NRRD string). These are public functions (no underscore before them), neatly organized and well-documented so users will know how to use the functions.
The purpose of having these functions is that it is quite common to add custom fields to the NRRD header for some reason and you may want to parse these fields. A great example is 3D Slicer for their segmentation NRRD files that add a bunch of fields.
The following NRRD types are defined as follows: (I've excluded any basic types like int, float, str or str list because they are pretty basic to convert to/from):
* vector - (1,2,3,4)
* optional vector - (1,2,3,4) …
> Add public parse and format functions for unknown fields

- README.md
Update recommended installation method in README to be using pip. 
Additionally, add link to the LICENSE in README.
> Update recommended installation method

- tests/test_nrrd.py
The previous method was converting to a byte string and comparing the strings. The main issue is that if the assertion fails, there will be no useful information in the trace about the data because it's one large string. By using Numpy's testing module, it will report statistics about how far off the matrix is, size of matrix and where the values are mismatched.
> Compare test Numpy arrays using Numpy.testing module

- nrrd.py
- tests/test_nrrd.py
- tests/test_simple4d_raw.nrrd
Perhaps it should? But it is currently only used for two fields, both of which should always parse as floats.
> parse_optional_matrix does not take 'dtype' kwarg

- requirements.txt
- setup.py
This was experimentally found to be a version of Numpy that successfully runs the pynrrd tests. It is likely that earlier versions of Numpy may work but the cutoff was just set here.
> Set minimum version for Numpy library to 1.11.1

- nrrd/tests/test_formatting.py
Issue was with using repr on Python 3.1 onwards which rounds floating point numbers to 12 decimals. The format_number function rounds to 17 digits which is what is required for full precision of a 64-bit floating point number.
See more information here: https://docs.python.org/3.4/tutorial/floatingpoint.html
The test was altered to use the decimal library and rounding to 17 points instead of using repr.
> Fix issue with test on format_numbers failing

- nrrd/tests/test_writing.py
- nrrd/writer.py
When reformatting the code (#58), the code was updated for writing detached NRRD files.
Added some tests for writing detached NRRD files in various encoding formats.
> Write tests for writing detached headers

- requirements.txt
The numpydoc package is used to support Numpy style docstrings in the pynrrd project. This is not installed on readthedocs and must be installed via requirements.txt file
> Add numpydoc requirement for readthedocs

- nrrd/reader.py
- nrrd/tests/test_reading.py
- nrrd/tests/test_writing.py
- nrrd/writer.py
- Allow override of duplicate field error, with a warning instead (occasionally occur with buggy writers)
- Allow changing the compression level - can significantly improve write performance at minimal space cost. As an illustrative example:
<details>
<summary>timing test details</summary>
```python
import nrrd
nrrd.reader._NRRD_ALLOW_DUPLICATE_FIELD = True
```
```python
img,hdr = nrrd.read("/path/to/dwi.nhdr")
%timeit -n1 -r1 nrrd.write("test.nrrd", img, hdr)
```
193 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
```python
hdr['encoding'] = 'gz'
%timeit -n1 -r1 nrrd.write("test_zl_9.nrrd", img, hdr)
```
20.2 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
```python
nrrd.writer._ZLIB_LEVEL = -1
hdr['encoding'] = 'gz'
%timeit -n1 -r1 …
```
> Allow override of dup. field error, and zlib compression level

- .gitignore
- nrrd/reader.py
- nrrd/tests/test_reading.py
When reading compressed data in pynrrd, the resulting numpy array is not writeable. This PR fixes the issue.
> Allow Numpy data to be written for compressed data

- docs/source/examples.rst
- docs/source/pynrrd.rst
- docs/source/user-guide.rst
- nrrd/reader.py
- nrrd/tests/test_reading.py
Documentation update to include the ALLOW_DUPLICATE_FIELD information (#71 )
I am not used to Sphinx, but I update it using the sphinx-doc by hand.
http://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html 
I hope it is close to the expected.
> Update the documentation with ALLOW_DUPLICATE_FIELD 

- AUTHORS
- nrrd/tests/test_writing.py
- nrrd/writer.py
Fixed a bug in the writer function where the header data was persistent between calls (see [this](https://docs.quantifiedcode.com/python-anti-patterns/correctness/mutable_default_value_as_argument.html) for further info).
> Fixed anti-pattern in writer function

- docs/source/README.rst
- docs/source/examples.rst
- nrrd/writer.py
Includes some minor fixes to the docs that were causing problems.
> Document that header object given to nrrd.write will be updated with auto generated fields

- docs/source/user-guide.rst
Simplify and reword content in the user guide of documentation. Felt there was some confusing and unnecessarily complex sentences. In addition, removed some content that is not relevant for a user interested in just getting started using `pynrrd`.
> Documentation Cleanup

- nrrd/reader.py
- nrrd/tests/test_reading.py
- nrrd/tests/util.py
Enable all warnings during tests to see additional problems in the code. The following warning appeared:
```
ResourceWarning: unclosed file <_io.BufferedReader name='<PYNRRD_DIR>\\nrrd\\tests\\data\\BallBinary30x30x30.raw'>
tb.tb_frame.clear()
```
Problem resolved by closing the file handle before raising errors. The only time this issue occurs is when the data is detached from the header. The detached data filename is loaded using an `open` call without a "with" block.
> Fix ResourceWarning from unclosed detached data NRRD files

- nrrd/reader.py
- nrrd/writer.py
This PR makes two changes to improve the performance of the `nrrd.write` function for compressed NRRD files, i.e. gzip or bzip2 compressed data.
The first change is to switch the decompressed data buffer from a `bytes` object to a `bytearray`. A `bytes` object is immutable and so appending to a `bytes` object requires that a new object is created in memory with the data. `bytearray` is a mutable object similar to `bytes` except that appending to the `bytearray` will result in adding the data to the array and allocating memory **only** if necessary. In addition, importing the data into a Numpy array is switched from `np.fromstring` to `np.frombuffer`. This is done because we no longer have a string **and** because there is a warning about `np.fromstring` being deprecated. Performance tests …
> Improve compressed NRRD read performance

- nrrd/writer.py
The GZIP library supports a compression level of `0` for no compression but this has been found to be slower than setting the encoding to `raw`. This PR removes documentation for setting `compression_level=0`. In addition, `bz2` in Python does not support a compression level of 0. Another benefit of this PR is the unified compression level range.
Note that the user can still specify a compression level of 0 at their own risk.
Fixes issue #88
> Remove documentation regarding compression_level=0

- docs/source/user-guide.rst
- nrrd/reader.py
- nrrd/tests/test_reading.py
- nrrd/tests/test_writing.py
- nrrd/writer.py
This is a proposal for the problem discussed in #75. This should probably be seen as a work-in-progress and a base for further discussion. I'm not sure whether this is the best approach so feedback would be appreciated.
The first addition is the `index_order` argument for `nrrd.read` which allows the user to specify the desired index order. I set the default to 'F' so the behavior should stay the same as with previous versions.
I also changed `nrrd.write`. This function did previously not work on C-contiguous arrays and this should now be fixed. Here I added an `index_order` flag, but my hope is that it should only be required in a few cases. Similar to most numpy functions there are three options; `F`, `C`, and `A`. The `A` (default) option automatically detects the order of the array. …
> Add parameter for changing index order

- README.rst
- setup.py
Remove tests from packaged distributions. Most users won't need to run the tests when they install `pynrrd`, so it is unnecessary files to pass along. In addition, the data was missing in order for the tests to run successfully.
Fixes #84
> Remove tests from setuptools

- nrrd/reader.py
- nrrd/tests/test_reading.py
This is the error message that would popup before this fix:
```
Size of the data does not equal to the product of all dimensions
```
Problem was that multiplying the dimensions together was overflowing the 32-bit result for larger than 4GB files.
Fixes #100
> Fix issue with loading large files

- nrrd/tests/test_writing.py
- nrrd/writer.py
Standardizes the output by replacing 'datafile' with 'data file'.
The NRRD spec seems to advocate for 'data file' over 'datafile'. There is a minor footnote mentioning that 'datafile' is allowed and 'data file' is used throughout their documentation.
Fixes #97
> Account for 'data file' and 'datafile' in header when writing NRRD file

- nrrd/tests/test_writing.py
- nrrd/writer.py
Ignore 'data file' and 'datafile' fields in the header.
Allow user to specify a custom data path via the detached_header
parameter. If its a string, then it's assumed to be a custom path.
Otherwise, if detached_header is set to True, then the filename for the
data will be calculated.
Fixes #96
> Change logic for how headers and detached data are written

- nrrd/writer.py
raw data encoding in writer did not have loop over chunks implemented. For me, in python 3.6.7, writing nrrds with raw encoding larger than ~2GB failed. Implementing this loop and writing in chunks resolved the issue. Some programs, notably in my case Paraview, do not read NRRD files with compression (which is silly) but for the time being I need to write nrrds with raw encoding.
> loop over write chunks added for raw encoding in writer

- nrrd/tests/test_writing.py
- nrrd/writer.py
Using the tostring function causes warnings like this starting in numpy 1.19:
DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
The simple fix is to replace them with tobytes which does the same thing.
Closes #110
> Fix numpy tostring warnings

- docs/source/examples.rst
- docs/source/user-guide.rst
Remove named argument usage for NRRD in examples docs. For `fh` and `header`, these should not be named since they are primary (i.e. not optional) arguments.
Update wording on docs for user-guide section.
> Update docs wording & example

- nrrd/tests/test_formatting.py
- nrrd/tests/test_parsing.py
- nrrd/tests/test_reading.py
- nrrd/tests/test_writing.py
- nrrd/tests/util.py
No longer needed since Python 2 support has been dropped
> Remove polyfill for assertRaisesRegex function in unittest module

- nrrd/tests/test_reading.py
- nrrd/tests/test_writing.py
- requirements.txt
* Make `TestReadingFunctions` & `TestWritingFunctions` subclass of `unittest.TestCase` for better type suggestions. However, since this test case is meant to be abstract, we nest the class in an `Abstract` class to prevent test discovery of this class.
* Add `index_order` typing for `TestReadingFunctions` and `TestWritingFunctions`
> Minor tweaking to read & write tests

- nrrd/reader.py
- nrrd/tests/test_reading.py
- nrrd/tests/test_writing.py
- nrrd/writer.py
Python f-string's are the preferred approach to formatting strings and is supported since Python 3.6. Replace remaining old-style string-formatting to use f-string style.
Additionally, refactor certain error messages to be consistent with others.
> Refactor string formatting to use f-strings

- nrrd/reader.py
- nrrd/tests/test_reading.py
Remove quotes from error message. Provides consistency with other error messages
> Minor formatting fix to error message

- setup.py
Prevent importing `nrrd` package in `setup.py` because this causes an error about `nptyping` package missing whilst running setup.py which is in the process of installing the packages.
The fix is to read the `_version.py` file specifically without importing the package.
> Do not load nrrd package in setup.py

- nrrd/tests/test_formatting.py
- nrrd/tests/test_parsing.py
- nrrd/tests/test_reading.py
Migrate from `np.NaN` to `np.nan`. The former was removed in NumPy >2
> Fix test failures for NumPy 2.0+

- docs/source/background/datatypes.rst
Found some minor typos in docs after review.
> Fix typos in docs

- .github/workflows/lint.yml
- .github/workflows/pythonpublish.yml
- .github/workflows/test.yml
- pyproject.toml
Pin Ubuntu version to 22.04 for all workflows. This fixes the issue with tests failing on Python 3.7 due to Python 3.7 not being available on the latest Ubuntu OS (see here: https://github.com/actions/setup-python/issues/962). Pinning the OS version on **all** workflows should limit unforeseen errors due to an a new latest OS.
Update Python version used in lint/publish workflows to 13. This is the latest available for Ubuntu 22.04.
Add Python 3.12 version to tests for CI. **Note:** Tests fail when testing with Python 3.13. This will be fixed in an upcoming PR.
Add Python 3.12/3.13 to list of supported versions.
> Fix tests failing in CI/CD

- .github/workflows/test.yml
- nrrd/reader.py
Fix warning regarding `maxsplit` argument in `re.split` being deprecated as a positional argument. In future Python versions, it will become an error and must be keyword-only.
Update Python test matrix to use 3.13.
> Fix Python 13 deprecation warning

- nrrd/reader.py
- nrrd/tests/test_reading.py
Fixes mhe/pynrrd#164
Note: this was a _very_ quick edit on a Friday afternoon before I log off for the week.
I have only run through a test in the case that the file is passed in (`fh_is_managed = True`), not in the other case (`fh_is_managed = False`). 
Please do make changes if needed
> Stop closing files opened by the caller

- .readthedocs.yaml
ReadTheDocs failed to build due to missing configuration key as mentioned here: https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/
Additionally, update the OS & Python version.
> Fix ReadTheDocs config
